name: wetland
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  auto_animated: ^3.0.0
  flip_card: ^0.5.0
  auto_size_text: ^2.1.0
  dio: ^3.0.10
  get_storage: ^2.0.2
  either_option: ^0.0.1
  connectivity: ^3.0.6
  lottie: ^1.0.1
  flick_video_player: ^0.3.1
  share: ^2.0.4
  path_provider: ^2.0.1
  downloads_path_provider_28: ^0.1.1
  permission_handler: ^4.4.0+hotfix.2
  open_file: ^3.0.1
  flutter_local_notifications: ^4.0.0
#  flutter_local_notifications: ^1.3.0
  percent_indicator: "^2.1.7+2"
  modal_bottom_sheet: ^1.0.0+1
  simple_gesture_detector: ^0.2.0
  multi_select_flutter: ^4.0.0
  jalali_calendar: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/lottie/
  fonts:
    - family: IranYekan
      fonts:
        - asset: asset/fonts/IRANYekanMobileLight.ttf
