// final String baseUrl = "http://192.168.1.10/projects/navid/public/api/";
import 'package:flutter/material.dart';
final String baseUrl = "http://apitalab.aserv.ir/public/api/";
// final String baseUrl = "http://80.210.32.126:9090/projects/kogaizirek/public/api/";
int timeOut = 7;
int pageSize = 15;
double borderRadius = 8.0;
Color pColor= Color(0xff9A8F75);
Color bgColor= Colors.white;
Color toggleColor = Color(0xffE8E1CD);
// Color bgColor= Color(0xffFBF3E3);